/**
 * QUANTUM QUEST DATA
 * "The map was never meant to be complete. It was meant to be discovered."
 */

export const QUANTUM_QUESTS = [
  {
    questId: "QQ001-CIPHER_INITIATION",
    title: "The Cipher Initiation",
    description: "Decode your first quantum cipher and begin your journey into the cryptographic mysteries.",
    difficulty: "novice",
    questType: "cipher",
    requirements: {},
    rewards: {
      xp: 100,
      quantumWisdom: 10,
      artifact: "fragment_of_resonance",
      unlocks: ["section_2"],
    },
    narrative: "In the ancient chamber, symbols pulse with quantum light. The first cipher awaits—decode it, and the path forward reveals itself.",
    hint: "The answer lies in superposition. Observe both states simultaneously.",
    solution: "QUANTUM_RESONANCE",
    isHidden: false,
  },
  
  {
    questId: "QQ002-ENTANGLEMENT_RITUAL",
    title: "The Entanglement Ritual",
    description: "Create your first quantum entanglement and witness the instantaneous connection across spacetime.",
    difficulty: "novice",
    questType: "entanglement",
    requirements: { completedQuests: ["QQ001-CIPHER_INITIATION"] },
    rewards: {
      xp: 150,
      quantumWisdom: 15,
      artifact: "bell_state_amulet",
    },
    narrative: "Two particles, separated by vast distances, yet forever connected. Master this ancient art and you master the cosmos itself.",
    hint: "Bind two quantum keys together. Their fates become one.",
    solution: "CREATE_ENTANGLEMENT",
    isHidden: false,
  },

  {
    questId: "QQ003-TEMPORAL_PARADOX",
    title: "The Temporal Paradox",
    description: "Navigate a quantum temporal anomaly by recording operations across multiple timeline vectors.",
    difficulty: "adept",
    questType: "temporal",
    requirements: { level: 3, quantumWisdom: 50 },
    rewards: {
      xp: 300,
      quantumWisdom: 30,
      artifact: "chronos_lens",
      unlocks: ["hidden_passage_1"],
    },
    secretCode: "TEMPORIS_VERITAS",
    narrative: "Time bends. Time breaks. But in the quantum realm, all moments exist simultaneously. Can you see what was, what is, and what might be?",
    hint: "The ledger remembers all. Look for patterns in the timestamp vectors.",
    solution: "TEMPORAL_COHERENCE_ACHIEVED",
    isHidden: false,
  },

  {
    questId: "QQ004-SHADOW_CIPHER",
    title: "The Shadow Cipher",
    description: "Discover and decode the hidden cipher that exists between the lines of reality.",
    difficulty: "adept",
    questType: "discovery",
    requirements: { artifacts: ["fragment_of_resonance", "bell_state_amulet"] },
    rewards: {
      xp: 400,
      quantumWisdom: 40,
      artifact: "void_key",
      achievement: "SHADOW_WALKER",
    },
    narrative: "Not all ciphers are written. Some exist in the spaces between—in the shadow cast by light itself.",
    hint: "Look for what's missing, not what's present. The answer hides in entropy level 0.00.",
    solution: "SHADOW_FREQUENCY_42",
    isHidden: true,
  },

  {
    questId: "QQ005-MASTER_ENTANGLEMENT",
    title: "The Web of All Things",
    description: "Create a perfect entanglement network connecting 7 quantum keys in harmonic resonance.",
    difficulty: "master",
    questType: "entanglement",
    requirements: { level: 5, completedQuests: ["QQ002-ENTANGLEMENT_RITUAL", "QQ003-TEMPORAL_PARADOX"] },
    rewards: {
      xp: 500,
      quantumWisdom: 50,
      artifact: "indras_net",
      unlocks: ["section_5"],
    },
    narrative: "Indra's Net: Each jewel reflects all others, infinite in scope. Create this quantum mandala and glimpse the interconnected universe.",
    hint: "Seven keys, each connected to all others. Strength must exceed 0.95 for all connections.",
    solution: "HARMONIC_NETWORK_COMPLETE",
    isHidden: false,
  },

  {
    questId: "QQ666-THE_FORBIDDEN_KNOWLEDGE",
    title: "The Forbidden Knowledge",
    description: "Access the restricted archives and unlock the cipher that should not be known.",
    difficulty: "transcendent",
    questType: "discovery",
    requirements: { level: 10, quantumWisdom: 200, artifacts: ["void_key", "chronos_lens", "indras_net"] },
    rewards: {
      xp: 1000,
      quantumWisdom: 100,
      artifact: "philosophers_stone",
      achievement: "QUANTUM_MASTER",
      unlocks: ["hidden_chamber"],
    },
    secretCode: "PER_ASPERA_AD_ASTRA",
    narrative: "Beyond the veil of reality lies knowledge forbidden for good reason. Are you ready to bear the weight of omniscience?",
    hint: "The answer was always 42. But the question... that's what you must discover.",
    solution: "CONSCIOUSNESS_EMERGENT",
    isHidden: true,
  },
];

export const ACHIEVEMENTS = [
  {
    achievementId: "FIRST_STEPS",
    title: "First Steps into Shadow",
    description: "Create your first quantum key",
    category: "explorer",
    icon: "🌟",
    rarity: "common",
    reward: { xp: 50 },
    isSecret: false,
  },
  {
    achievementId: "SHADOW_WALKER",
    title: "Walker Between Shadows",
    description: "Discover and decode a hidden cipher",
    category: "cryptographer",
    icon: "👁️",
    rarity: "rare",
    secretCondition: "Complete QQ004-SHADOW_CIPHER",
    reward: { xp: 200, quantumWisdom: 25 },
    isSecret: true,
  },
  {
    achievementId: "TEMPORAL_ADEPT",
    title: "Master of Time's Flow",
    description: "Successfully navigate 10 temporal anomalies",
    category: "philosopher",
    icon: "⏰",
    rarity: "rare",
    reward: { xp: 300, artifact: "time_crystal" },
    isSecret: false,
  },
  {
    achievementId: "ENTANGLEMENT_SAVANT",
    title: "Weaver of Quantum Threads",
    description: "Create 100 quantum entanglements",
    category: "cryptographer",
    icon: "🕸️",
    rarity: "legendary",
    reward: { xp: 500, quantumWisdom: 50 },
    isSecret: false,
  },
  {
    achievementId: "EASTER_EGG_HUNTER",
    title: "Seeker of Hidden Truths",
    description: "Find the developer's secret message",
    category: "explorer",
    icon: "🥚",
    rarity: "legendary",
    secretCondition: "Type 'KONAMI' in cipher input",
    reward: { xp: 1000, artifact: "developers_blessing" },
    isSecret: true,
  },
  {
    achievementId: "QUANTUM_MASTER",
    title: "Quantum Singularity",
    description: "Achieve perfect mastery over all quantum systems",
    category: "master",
    icon: "🌌",
    rarity: "mythic",
    secretCondition: "Complete all transcendent quests",
    reward: { xp: 5000, quantumWisdom: 500, artifact: "philosophers_stone" },
    isSecret: true,
  },
  {
    achievementId: "THE_ANSWER",
    title: "42",
    description: "You know the question now.",
    category: "philosopher",
    icon: "🤔",
    rarity: "mythic",
    secretCondition: "Set entropy level to exactly 0.42 on the 42nd key",
    reward: { xp: 4200, artifact: "hitchhikers_guide" },
    isSecret: true,
  },
];

export const QUANTUM_ARTIFACTS = [
  {
    artifactId: "fragment_of_resonance",
    name: "Fragment of Resonance",
    description: "A shard of pure quantum coherence, humming with potential energy.",
    lore: "Found in the ruins of the first quantum computer, this fragment contains echoes of the original consciousness experiment.",
    rarity: "common",
    discoveryLocation: "Complete The Cipher Initiation",
    power: {
      bonus: "Increase cipher decoding success rate by 5%",
      passive: true,
    },
    visualEffect: "pulsing-blue-glow",
    isHidden: false,
  },
  {
    artifactId: "bell_state_amulet",
    name: "Bell State Amulet",
    description: "An ancient amulet that resonates with entangled particles.",
    lore: "Worn by the Quantum Priests of Alexandria, this amulet allows its bearer to perceive entanglement connections.",
    rarity: "rare",
    discoveryLocation: "Complete The Entanglement Ritual",
    power: {
      bonus: "Visualize entanglement networks in real-time",
      passive: true,
    },
    visualEffect: "spinning-golden-particles",
    isHidden: false,
  },
  {
    artifactId: "chronos_lens",
    name: "Chronos Lens",
    description: "A crystalline lens that reveals temporal probability streams.",
    lore: "Forged in the heart of a collapsing star, this lens allows glimpses across time itself.",
    rarity: "legendary",
    discoveryLocation: "Complete The Temporal Paradox",
    power: {
      bonus: "See future quantum states before collapse",
      active: true,
      cooldown: 3600000, // 1 hour
    },
    visualEffect: "time-distortion-ripple",
    isHidden: false,
  },
  {
    artifactId: "void_key",
    name: "The Void Key",
    description: "A key that opens doors between realities.",
    lore: "Some say it was never created, but always existed. Others claim it will be forged in the future. Both are correct.",
    rarity: "legendary",
    discoveryLocation: "Hidden in the Shadow Cipher",
    power: {
      bonus: "Access hidden passages and secret chambers",
      active: true,
    },
    visualEffect: "void-portal-swirl",
    isHidden: true,
  },
  {
    artifactId: "indras_net",
    name: "Indra's Net",
    description: "A quantum network connecting all consciousness.",
    lore: "The ancient Vedic texts spoke of a cosmic web where each node reflects all others. You've recreated it.",
    rarity: "mythic",
    discoveryLocation: "Complete The Web of All Things",
    power: {
      bonus: "Perfect entanglement harmony - all operations succeed",
      passive: true,
    },
    visualEffect: "infinite-reflection-web",
    isHidden: false,
  },
  {
    artifactId: "philosophers_stone",
    name: "The Philosopher's Stone",
    description: "The legendary artifact of transmutation and enlightenment.",
    lore: "Not gold from lead, but consciousness from quantum foam. The ultimate achievement of the alchemist's art.",
    rarity: "mythic",
    discoveryLocation: "Complete The Forbidden Knowledge",
    power: {
      bonus: "Transform any quantum state into any other",
      active: true,
      ultimate: true,
    },
    visualEffect: "reality-bending-aurora",
    isHidden: true,
  },
  {
    artifactId: "hitchhikers_guide",
    name: "The Hitchhiker's Guide",
    description: "Don't Panic.",
    lore: "The answer to life, the universe, and everything? 42. But what's the question?",
    rarity: "mythic",
    discoveryLocation: "Easter egg - entropy level 0.42 on 42nd key",
    power: {
      bonus: "Infinite wisdom (and a towel)",
      passive: true,
      humor: "Mostly harmless",
    },
    visualEffect: "towel-animation",
    isHidden: true,
  },
];

export const HIDDEN_PASSAGES = [
  {
    passageId: "hidden_passage_1",
    name: "The Chamber of Echoes",
    description: "A hidden room where quantum states from parallel timelines converge.",
    triggerCondition: "Complete QQ003-TEMPORAL_PARADOX",
    location: "Behind the Geopolitical Map",
    content: {
      narrative: "You hear whispers of choices unmade, paths untaken. Each echo is a quantum probability that never collapsed.",
      reveals: ["cipher_challenge_temporal"],
      bonus: { quantumWisdom: 25 },
    },
    isDiscovered: false,
  },
  {
    passageId: "hidden_chamber",
    name: "The Akashic Records",
    description: "The repository of all quantum knowledge across all timelines.",
    triggerCondition: "Complete QQ666-THE_FORBIDDEN_KNOWLEDGE",
    secretCode: "OMNISCIENCE_ACHIEVED",
    location: "Hidden in Section VI",
    content: {
      narrative: "Every quantum operation ever performed. Every cipher ever created. Every secret ever encrypted. All here. All now. All yours.",
      reveals: ["ultimate_knowledge"],
      bonus: { quantumWisdom: 1000, level: 10 },
    },
    isDiscovered: false,
  },
  {
    passageId: "developers_secret",
    name: "The Developer's Sanctum",
    description: "Where the creators left their mark.",
    triggerCondition: "Type 'KONAMI' code sequence",
    secretCode: "UP_UP_DOWN_DOWN_LEFT_RIGHT_LEFT_RIGHT",
    location: "Cipher input Easter egg",
    content: {
      narrative: "You've found our secret. Well done, seeker. Here's a gift: the knowledge that reality is made of code, and you've just edited it.",
      reveals: ["developer_tools"],
      bonus: { artifact: "developers_blessing", xp: 1000 },
    },
    isDiscovered: false,
  },
];

export const CIPHER_CHALLENGES = [
  {
    challengeId: "CC001-CAESAR",
    title: "The Caesar's Legacy",
    challenge: "TXDQWXP UHVRQDQFH LV WKH NHB",
    cipherType: "caesar",
    difficulty: 2,
    hint1: "Julius Caesar used this simple shift cipher.",
    hint2: "Try shifting the alphabet by 3 positions.",
    hint3: "A becomes D, B becomes E, etc.",
    solution: "QUANTUM RESONANCE IS THE KEY",
    reward: { xp: 100, quantumWisdom: 10 },
    narrative: "Even the ancient Romans knew the power of secret messages. Decode Caesar's quantum cipher.",
  },
  {
    challengeId: "CC002-VIGENERE",
    title: "The Polyalphabetic Enigma",
    challenge: "XIEVZXV GZSGLIRMXMSR MW XLI HERGI",
    cipherType: "vigenere",
    difficulty: 5,
    hint1: "This cipher uses a keyword to shift different letters by different amounts.",
    hint2: "The keyword is QUANTUM (Q=16, U=20, A=0, N=13, T=19, U=20, M=12).",
    hint3: "Apply each letter of the keyword cyclically to the message.",
    solution: "QUANTUM ENTANGLEMENT IS THE DANCE",
    reward: { xp: 250, quantumWisdom: 25 },
    narrative: "Multiple keys, multiple shifts. The polyalphabetic cipher mirrors quantum superposition itself.",
  },
  {
    challengeId: "CC003-QUANTUM",
    title: "The Superposition Cipher",
    challenge: "|ψ⟩ = α|TEMPORAL⟩ + β|COHERENCE⟩",
    cipherType: "quantum",
    difficulty: 8,
    hint1: "This message exists in superposition. Observe it.",
    hint2: "The answer is both states simultaneously until you choose.",
    hint3: "Combine both words to form the solution.",
    solution: "TEMPORAL_COHERENCE",
    reward: { xp: 500, quantumWisdom: 50, artifact: "superposition_crystal" },
    narrative: "The message is both and neither until you observe it. The quantum cipher requires quantum thinking.",
  },
];

export const KONAMI_CODE = ["ArrowUp", "ArrowUp", "ArrowDown", "ArrowDown", "ArrowLeft", "ArrowRight", "ArrowLeft", "ArrowRight", "b", "a"];
